AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS Hail Quickstart (qs-1qp776mh2)"

Metadata:
  QuickStartDocumentation:
    EntrypointName: "Launch into a new VPC"
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Network Configuration"
        Parameters:
          - "VPCTarget"
          - "VPCCIDR"
          - "VPCId"
          - "VPCSubnetId"
          - "VPCSubnetType"
      - Label:
          default: "Hail Configuration"
        Parameters:
          - "HailS3BucketName"
          - "CreateHailBucket"
          - "SageMakerS3BucketName"
          - "CreateSageMakerBucket"
          - "KMSEbsKeyArn"
      - Label:
          default: "Tagging Configuration"
        Parameters:
          - "TagEnvironmentType"
          - "TagOwner"
      - Label:
          default: "AWS Quick Start Configuration"
        Parameters:
         - "QSS3BucketName"
         - "QSS3KeyPrefix"
      
    ParameterLabels:
      QSS3BucketName:
        default: Quick Start S3 bucket name
      QSS3KeyPrefix:
        default: Quick Start S3 key prefix
      KMSEbsKeyArn:
        default: "EBS KMS Key ARN"
      HailS3BucketName:
        default: "Hail S3 Bucket Name"
      CreateHailBucket:
        default: "Create Hail S3 Bucket"
      SageMakerS3BucketName:
        default: "Sagemaker Home Directory S3 Bucket Name"
      CreateSageMakerBucket:
        default: "Create SageMaker Home Directory S3 Bucket"
      TagOwner:
        default: "Owner"
      TagEnvironmentType:
        default: "Environment Type"
      VPCTarget:
        default: "VPC Target"
      VPCCIDR:
        default: "New VPC CIDR"
      VPCId:
        default: "Existing VPC ID"
      VPCSubnetId:
        default: "Existing Subnet ID"
      VPCSubnetType:
        default: "Existing Subnet Type"
        
Parameters:

  QSS3BucketName:
    AllowedPattern: "^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    ConstraintDescription: "Quick Start bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-)."
    Default: "aws-quickstart"
    Description: "S3 bucket name for the Quick Start assets. Quick Start bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-)."
    Type: "String"

  QSS3KeyPrefix:
    AllowedPattern: "^[0-9a-zA-Z-/]*$"
    ConstraintDescription: "Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)."
    Default: "quickstart-hail/"
    Description: "S3 key prefix for the Quick Start assets. Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)."
    Type: "String"

  KMSEbsKeyArn:
    Description: "(Optional) The full KMS Key ARN if region level EBS encryption is enabled. Note, this does NOT automatically encrypt your AMI."
    Default: ""
    Type: "String"

  HailS3BucketName:
    AllowedPattern: "^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    Description: "The name of the S3 bucket that stores EMR logs, cluster manifests, and VEP configuration files."
    Type: "String"

  CreateHailBucket:
    Type: "String"
    Description: "Select No to use an existing bucket."
    AllowedValues:
      - "yes"
      - "no"
    Default: "yes"

  SageMakerS3BucketName:
    AllowedPattern: "^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    Description: "The name of the S3 bucket for common notebooks and SageMaker home directory backups."
    Type: "String"

  CreateSageMakerBucket:
    Type: "String"
    Description: "Select No to use an existing bucket."
    AllowedValues:
      - "yes"
      - "no"
    Default: "yes"

  TagEnvironmentType:
    AllowedValues:
      - "production"
      - "staging"
      - "development"
    Default: "development"
    Description: "Environment type for default resource tagging."
    Type: "String"

  TagOwner:
    Type: "String"
    Description: "(Optional) Owner for default resource tagging. Suggested values are <User Name>, <Department Name>, <Project Name>, etc."
    Default: ""

  VPCTarget:
    Type: "String"
    Description: "Choose \"new\" to use the AWS VPC Quickstart to create a new VPC with 3 public and 3 private subnets. If you choose \"existing\", VPCId and SubnetId network parameters are required."
    AllowedValues:
      - "new"
      - "existing"
    Default: "existing"

  VPCCIDR:
    Type: "String"
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    Description: "Required for a new VPC. A /16 address space is recommended for a new VPC."
    Default: "10.0.0.0/16"

  VPCId:
    Description: "Required for existing VPC target."
    Type: "String"
    Default: ""

  VPCSubnetId:
    Description: "Required for an existing VPC target. Subnet ID in the existing VPC in which EMR Cluster and SageMaker Notebook Instances will be launched. A private subnet is recommended."
    Type: "String"
    Default: ""

  VPCSubnetType:
    Description: "Required for an existing VPC target. Should match the type of subnet specified by Subnet Id. Type of subnet compute resources will be deployed in and also used to create custom AMIs. A private is recommended."
    Type: "String"
    AllowedValues:
      - "public"
      - "private"
    Default: "private"

Conditions:

    createVpc: !Equals [!Ref VPCTarget, "new"]

Resources:

  core:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}templates/hail-core.template.yaml"
      Parameters:
        pHailBucket: !Ref HailS3BucketName
        pCreateHailBucket: !Ref CreateHailBucket
        pKmsEbsArn: !Ref KMSEbsKeyArn
        pSageMakerBucket: !Ref SageMakerS3BucketName
        pCreateSageMakerBucket: !Ref CreateSageMakerBucket
        pSubnetId: !If [createVpc, !GetAtt 'vpc.Outputs.PrivateSubnet1AID', !Ref VPCSubnetId]
        pSubnetType: !If [createVpc, "private", !Ref VPCSubnetType]
        pTagEnvironment: !Ref TagEnvironmentType
        pTagOwner: !Ref TagOwner
        pVpcId: !If [createVpc, !GetAtt 'vpc.Outputs.VPCID', !Ref VPCId]
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
      TimeoutInMinutes: 5

  vpc:
    Type: "AWS::CloudFormation::Stack"
    Condition: createVpc
    Properties:
      TemplateURL: !Sub "https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}submodules/quickstart-aws-vpc/templates/aws-vpc.template"
      Parameters:
        AvailabilityZones: !Join
        - ','
        - - !Select
            - 0
            - Fn::GetAZs: !Ref 'AWS::Region'
          - !Select
            - 1
            - Fn::GetAZs: !Ref 'AWS::Region'
        VPCCIDR: !Ref VPCCIDR
        PublicSubnet1CIDR: !Select [ 0, !Cidr [ !Ref VPCCIDR, 6, 12 ]]
        PrivateSubnet1ACIDR: !Select [ 1, !Cidr [ !Ref VPCCIDR, 6, 12 ]]
        PrivateSubnet1BCIDR: !Select [ 2, !Cidr [ !Ref VPCCIDR, 6, 12 ]]
        PublicSubnet2CIDR: !Select [ 3, !Cidr [ !Ref VPCCIDR, 6, 12 ]]
        PrivateSubnet2ACIDR: !Select [ 4, !Cidr [ !Ref VPCCIDR, 6, 12 ]]
        PrivateSubnet2BCIDR: !Select [ 5, !Cidr [ !Ref VPCCIDR, 6, 12 ]]
      TimeoutInMinutes: 10

Outputs:

  portfolio:
    Description: "Service Catalog Portfolio"
    Value: !GetAtt core.Outputs.portfolio

  codeBuildConsole:
    Description: "CodeBuild Project Console URL"
    Value: !Sub "https://console.aws.amazon.com/codesuite/codebuild/projects?region=${AWS::Region}"

  bucketHail:
    Description: "Hail S3 Bucket"
    Value: !GetAtt core.Outputs.bucketHail

  bucketSageMaker:
    Description: "SageMaker S3 Bucket"
    Value: !GetAtt core.Outputs.bucketSageMaker
